version: '3'
networks:
  sheila-net:
    driver: bridge
volumes:
    sheila_prometheus_data: {}
    sheila_grafana_data: {}
services:
  sheila:
    image: sheila:latest
    container_name: sheila-main
    ports:
      - "2112"
    networks:
      - sheila-net
    environment:
      - SHEILA_USER=${SHEILA_USER}

  prometheus:
    image: prom/prometheus:latest
    container_name: sheila-prom
    volumes:
      - sheila_prometheus_data:/prometheus
      - ../configs/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=31d'
      - '--web.enable-lifecycle'
    # restart: unless-stopped
    ports:
      - "9090"
    networks:
      - sheila-net

  grafana:
    image: grafana/grafana:latest
    container_name: sheila-grafana
    #restart: unless-stopped
    volumes:
      - sheila_grafana_data:/var/lib/grafana
      - ../configs/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000"
    networks:
      - sheila-net