{
 "title": "SHEILA",
 "description": "Information about the DEMI application.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature, Brightness, Presence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "expr": "sheila_hue_worker_sensor_gauge{type=\"ZLLTemperature\"}/100 * 9/5 + 32",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Motion",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sheila_hue_worker_sensor_gauge{type=\"ZLLPresence\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Light Level",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    {
     "expr": "10 ^ ((sheila_hue_worker_sensor_gauge{type=\"ZLLLightLevel\"} - 1) / 10000)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Lights - On/Off",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sheila_hue_worker_light_gauge{state=\"on\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Application Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Version",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sheila_sheila_info", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Sensor Batteries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sheila_hue_worker_sensor_gauge{type=\"battery\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sensors - Reachable",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sheila_hue_worker_sensor_gauge{type=\"reachable\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Lights - Reachable",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sheila_hue_worker_light_gauge{state=\"reachable\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(sheila_hue_client_command_duration_seconds_sum{statusCode!=\"-1\"}[5m])\n/\nrate(sheila_hue_client_command_duration_seconds_sum{statusCode!=\"-1\"}[5m])",
     "legendFormat": "{{url}} with {{statusCode}}"
    }
   ]
  },
  { "title": "Go Process Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Process CPU Seconds over 5m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m]) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Go Process Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}} - resident" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{job}} - virtual" }
   ]
  },
  {
   "title": "Go Memstats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{job}} - bytes allocated" },
    {
     "expr": "rate(go_memstats_alloc_bytes_total[30s])",
     "legendFormat": "{{job}} - alloc rate"
    },
    { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "{{job}} - stack inuse" },
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{job}} - heap inuse" }
   ]
  },
  {
   "title": "Go Open FDS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "{{job}}" }
   ]
  }
 ]
}